# Application template.
apiVersion: v1
kind: Template
metadata:
  name: se-service-template-app-template
  namespace: test
  annotations:
    description: This template defines objects that are required to spin up an se-service-template service pod
    tags: se-service-template, service
    openshift.io/display-name: se-service-template-template
    openshift.io/long-description: This template provides objects that are required to spin up a se-service-template service pod.
    openshift.io/provider-display-name: SumelongEnterprise
labels:
  app: se-service-template-app
  createdBy: SumelongEnterprise-Team
items:
  -
    apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: se-service-template
    spec:
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 600
          maxUnavailable: 25%
          maxSurge: 25%
          pre:
            failurePolicy: ignore
            execNewPod:
              command:
                - "/bin/sh"
                - "-c"
                - |
                    while true
                    do
                      rt=$(nc -z -w 1 mysql 80)
                      if [ $? -eq 0 ]; then
                        echo "DB is UP"
                        break
                      fi
                      echo "DB is not yet reachable;sleep for 10s before retry"
                      sleep 10
                    done
              containerName: se-service-template
        resources:
      replicas: "1"
      template:
        metadata:
          labels:
            app: se-service-template
        spec:
          containers:
          - name: se-service-template
            image: docker.io/springcloud/eureka
            imagePullPolicy: IfNotPresent
            env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod,swagger
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql/se-service-template?useUnicode=true&characterEncoding=utf8&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-persistent-8n2hx-credentials-v8pwh
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-persistent-8n2hx-credentials-v8pwh
                  key: password
            - name: SECURITY_FILTER_DATASOURCE_URL
              value: jdbc:mysql://mysql/se-security-filter?useUnicode=true&characterEncoding=utf8&useSSL=false
            - name: SECURITY_FILTER_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-persistent-8n2hx-credentials-v8pwh
                  key: username
            - name: SECURITY_FILTER_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-persistent-8n2hx-credentials-v8pwh
                  key: password
            ports:
            - name: http
              containerPort: "8080"
  -
    apiVersion: v1
    kind: Service
    metadata:
      annotations:
        service.alpha.openshift.io/dependencies: '[{
          "name":"mysql", "namespace": "", "kind": "Service"}]'
      labels:
        app: se-service-template
      name: se-service-template
    spec:
      selector:
        app: se-service-template
      type: LoadBalancer
      ports:
      - name: http
        port: "8080"
  -
    apiVersion: v1
    kind: Route
    metadata:
      name: se-service-template
    spec:
      to:
        kind: Service
        name: se-service-template
        weight: "100"
      port:
        targetPort: "http"
      wildcardPolicy: None
